version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - /var/postgres:/var/postgres
    env_file:
      - docker.env
    networks:
      - my_api_network

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - my_api_network

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - /var/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - my_api_network

networks:
  my_api_network:
    driver: bridge
